export const UPDATE_MOVIES = "UPDATE_MOVIES";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const FETCHING_MOVIES = "FETCHING_MOVIES";
export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const RESET_FILTERS = "RESET_FILTERS";
export const ERROR_GET_MOVIES = "ERROR_GET_MOVIES";

